"""new migration

Revision ID: 253a8416bce9
Revises: 5cb65dc2c98b
Create Date: 2020-07-01 10:47:21.762249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '253a8416bce9'
down_revision = '5cb65dc2c98b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###
